version: "3.8"

services:
#-------------------------------------------------------------------#
  frontend:
    build: ./frontend-react
    ports:
      - "3000:3000"
#-------------------------------------------------------------------#
  backend: 
    build: ./backend-api
    ports:
      - "3001:3001"
    environment:
      DB_URL: mongodb://db/zaksApp
#-------------------------------------------------------------------#
  db:
    image: mongo:4.0.28-xenial
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - zaksApp:/data/db
#-------------------------------------------------------------------#
volumes:
  zaksApp:
  

